def weather_symbol(weather_forecast):
    if weather_forecast in [1]: #sun
        image =("-------y--------\n"
                "-------y--------\n"
                "---y-------y----\n"
                "----y--y--y-----\n"
                "------yyy-------\n"
                "-----yyyyy------\n"
                "-----yyyyy------\n"
                "--yy-yyyyy-yy---\n"
                "-----yyyyy------\n"
                "------yyy-------\n"
                "----y--y--y-----\n"
                "---y-------y----\n"
                "-------y--------\n"
                "-------y--------")
    elif weather_forecast in [0]:#moon
        image =("--------ooo-----\n"
                "------ooo-------\n"
                "-----oooo-------\n"
                "----oooo--------\n"
                "----ooo---------\n"
                "---oooo---------\n"
                "---oooo---------\n"
                "---oooo---------\n"
                "---oooo---------\n"
                "----ooo---------\n"
                "----oooo--------\n"
                "-----oooo-------\n"
                "------ooo-------\n"
                "--------ooo-----")
    elif weather_forecast in [2]: #cloud moon
        image =("----------------\n"
                "-----------ooo--\n"
                "---------ooo----\n"
                "--------oooo----\n"
                "----WWW-ooo-----\n"
                "---WwwwW-ooo----\n"
                "-WWwwwwwW-oo----\n"
                "WwwWwwwwWWW-oo--\n"
                "WwwwwwwWwwwW----\n"
                "WwwwwwwwwwwW----\n"
                "-WWWWWWWWWW-----\n"
                "----------------\n"
                "----------------\n"
                "----------------")
    elif weather_forecast in [3]: #cloud sun
        image =("----------------\n"
                "----------------\n"
                "----WWW---y-----\n"
                "---WwwwW--y--y--\n"
                "-WWwwwwwW---y---\n"
                "WwwWwwwwWWW-----\n"
                "WwwwwwwWwwwW-yy-\n"
                "WwwwwwwwwwwW----\n"
                "-WWWWWWWWWW-----\n"
                "------------y---\n"
                "----------y--y--\n"
                "----------y-----\n"
                "----------------\n"
                "----------------")
    elif weather_forecast in [5]: #mist
        image =("----------------\n"
                "----------------\n"
                "----------------\n"
                "----------------\n"
                "w---w-w-www-www-\n"
                "ww-ww-w-w----w--\n"
                "w-w-w-w-www--w--\n"
                "w---w-w---w--w--\n"
                "w---w-w---w--w--\n"
                "w---w-w-www--w--\n"
                "----------------\n"
                "----------------\n"
                "----------------\n"
                "----------------")
    elif weather_forecast in [6]: #fog
        image =("----------------\n"
                "----------------\n"
                "----------------\n"
                "----------------\n"
                "-wwww-wwww-wwww-\n"
                "-w----w--w-w----\n"
                "-www--w--w-w----\n"
                "-w----w--w-w-ww-\n"
                "-w----w--w-w--w-\n"
                "-w----wwww-wwww-\n"
                "----------------\n"
                "----------------\n"
                "----------------\n"
                "----------------")
    elif weather_forecast in [7]:
        image =("----------------\n"
                "----------------\n"
                "-----WWWWW------\n"
                "----WwwwwwW-----\n"
                "---WwwwwwwwW----\n"
                "-WWWwwwwwwwW----\n"
                "WwwwWwwwwwwWWW--\n"
                "WwwwwwwwwWWwwwW-\n"
                "WwwwwwwwwwwwwwW-\n"
                "WWwwwwwwwwwwwwW-\n"
                "-WWWWWWWWWWWWW--\n"
                "----------------\n"
                "----------------\n"
                "----------------")
    elif weather_forecast in [8]:  #dark cloud
        image =("----------------\n"
                "----------------\n"
                "-----wwwww------\n"
                "----w-----w-----\n"
                "---w-------w----\n"
                "-www-------w----\n"
                "w---w------www--\n"
                "w--------ww---w-\n"
                "w-------------w-\n"
                "ww------------w-\n"
                "-wwwwwwwwwwwww--\n"
                "----------------\n"
                "----------------\n"
                "----------------")
    elif weather_forecast in [9]: #cloud moon rain
        image =("----------------\n"
                "-----------ooo--\n"
                "---------ooo----\n"
                "--------oooo----\n"
                "----www-ooo-----\n"
                "---w---w-ooo----\n"
                "-ww-----w-oo----\n"
                "w--w----www-oo--\n"
                "w------w---w----\n"
                "w----------w----\n"
                "-wwwwwwwwww-----\n"
                "---C------------\n"
                "---C--C---------\n"
                "------C---------")
    elif weather_forecast in [10]: #cloud sun rain
        image =("----------------\n"
                "----------------\n"
                "----www---y-----\n"
                "---w---w--y--y--\n"
                "-ww-----w---y---\n"
                "w--w----www-----\n"
                "w------w---w-yy-\n"
                "w----------w----\n"
                "-wwwwwwwwww-----\n"
                "---C--------y---\n"
                "---C--C---y--y--\n"
                "------C---y-----\n"
                "----------------\n"
                "----------------")
    elif weather_forecast in [11]: #drizzle
        image =("----------------\n"
                "----------------\n"
                "------www-------\n"
                "-----w---w------\n"
                "---ww-----w-----\n"
                "--w--w----www---\n"
                "--w------w---w--\n"
                "--w----------w--\n"
                "---wwwwwwwwww---\n"
                "----------------\n"
                "-----c--c--c----\n"
                "----------------\n"
                "-----c--c--c----\n"
                "----------------")
    elif weather_forecast in [12]: #light rain
        image =("----------------\n"
                "----------------\n"
                "------www-------\n"
                "-----w---w------\n"
                "---ww-----w-----\n"
                "--w--w----www---\n"
                "--w------w---w--\n"
                "--w----------w--\n"
                "---wwwwwwwwww---\n"
                "-----C----------\n"
                "-----C--C-------\n"
                "--------C-------\n"
                "----------------\n"
                "----------------")
    elif weather_forecast in [13]: #heavy rain cloud moon
        image =("----------------\n"
                "-----------ooo--\n"
                "---------ooo----\n"
                "--------oooo----\n"
                "----www-ooo-----\n"
                "---w---w-ooo----\n"
                "-ww-----w-oo----\n"
                "w--w----www-oo--\n"
                "w------w---w----\n"
                "w----------w----\n"
                "-wwwwwwwwww-----\n"
                "---B-----B------\n"
                "---B--B--B------\n"
                "------B---------")
    elif weather_forecast in [14]: #heavy rain cloud sun
        image =("----------------\n"
                "----------------\n"
                "----www---y-----\n"
                "---w---w--y--y--\n"
                "-ww-----w---y---\n"
                "w--w----www-----\n"
                "w------w---w-yy-\n"
                "w----------w----\n"
                "-wwwwwwwwww-----\n"
                "--B-----B---y---\n"
                "--B--B--B-y--y--\n"
                "-----B----y-----\n"
                "----------------\n"
                "----------------")
    elif weather_forecast in [15]: #heavy rain
        image =("----------------\n"
                "----------------\n"
                "------www-------\n"
                "-----w---w------\n"
                "---ww-----w-----\n"
                "--w--w----www---\n"
                "--w------w---w--\n"
                "--w----------w--\n"
                "---wwwwwwwwww---\n"
                "-----B-----B----\n"
                "-----B--B--B----\n"
                "--------B-------\n"
                "----------------\n"
                "----------------")
    elif weather_forecast in [16]: #sleet cloud moon
        image =("----------------\n"
                "-----------ooo--\n"
                "---------ooo----\n"
                "--------oooo----\n"
                "----www-ooo-----\n"
                "---w---w-ooo----\n"
                "-ww-----w-oo----\n"
                "w--w----www-oo--\n"
                "w------w---w----\n"
                "w----------w----\n"
                "-wwwwwwwwww-----\n"
                "----------------\n"
                "---W--C--W------\n"
                "------C---------")
    elif weather_forecast in [17]: #sleet cloud sun
        image =("----------------\n"
                "----------------\n"
                "----www---y-----\n"
                "---w---w--y--y--\n"
                "-ww-----w---y---\n"
                "w--w----www-----\n"
                "w------w---w-yy-\n"
                "w----------w----\n"
                "-wwwwwwwwww-----\n"
                "------------y---\n"
                "--W--C--W-y--y--\n"
                "-----C----y-----\n"
                "----------------\n"
                "----------------")
    elif weather_forecast in [18]: #sleet
        image =("----------------\n"
                "----------------\n"
                "------www-------\n"
                "-----w---w------\n"
                "---ww-----w-----\n"
                "--w--w----www---\n"
                "--w------w---w--\n"
                "--w----------w--\n"
                "---wwwwwwwwww---\n"
                "----------------\n"
                "-----W--C--W----\n"
                "--------C-------\n"
                "----------------\n"
                "----------------")
    elif weather_forecast in [19]: #hail cloud moon
        image =("----------------\n"
                "-----------ooo--\n"
                "---------ooo----\n"
                "--------oooo----\n"
                "----www-ooo-----\n"
                "---w---w-ooo----\n"
                "-ww-----w-oo----\n"
                "w--w----www-oo--\n"
                "w------w---w----\n"
                "w----------w----\n"
                "-wwwwwwwwww-----\n"
                "----------------\n"
                "---WW---WW------\n"
                "----------------")
    elif weather_forecast in [20]: #hail cloud sun
        image =("----------------\n"
                "----------------\n"
                "----www---y-----\n"
                "---w---w--y--y--\n"
                "-ww-----w---y---\n"
                "w--w----www-----\n"
                "w------w---w-yy-\n"
                "w----------w----\n"
                "-wwwwwwwwww-----\n"
                "------------y---\n"
                "--WW---WW-y--y--\n"
                "----------y-----\n"
                "----------------\n"
                "----------------")
    elif weather_forecast in [21]: #hail
        image =("----------------\n"
                "----------------\n"
                "------www-------\n"
                "-----w---w------\n"
                "---ww-----w-----\n"
                "--w--w----www---\n"
                "--w------w---w--\n"
                "--w----------w--\n"
                "---wwwwwwwwww---\n"
                "----------------\n"
                "----WW---WW-----\n"
                "----------------\n"
                "----------------\n"
                "----------------")
    elif weather_forecast in [22]: #light snow cloud moon
        image =("----------------\n"
                "-----------ooo--\n"
                "---------ooo----\n"
                "--------oooo----\n"
                "----www-ooo-----\n"
                "---w---w-ooo----\n"
                "-ww-----w-oo----\n"
                "w--w----www-oo--\n"
                "w------w---w----\n"
                "w----------w----\n"
                "-wwwwwwwwww-----\n"
                "----------------\n"
                "---W-----W------\n"
                "------W---------")
    elif weather_forecast in [23]: #light snow cloud sun
        image =("----------------\n"
                "----------------\n"
                "----www---y-----\n"
                "---w---w--y--y--\n"
                "-ww-----w---y---\n"
                "w--w----www-----\n"
                "w------w---w-yy-\n"
                "w----------w----\n"
                "-wwwwwwwwww-----\n"
                "------------y---\n"
                "--W-----W-y--y--\n"
                "-----W----y-----\n"
                "----------------\n"
                "----------------")
    elif weather_forecast in [24]: #light snow
        image =("----------------\n"
                "----------------\n"
                "------www-------\n"
                "-----w---w------\n"
                "---ww-----w-----\n"
                "--w--w----www---\n"
                "--w------w---w--\n"
                "--w----------w--\n"
                "---wwwwwwwwww---\n"
                "----------------\n"
                "-----W-----W----\n"
                "--------W-------\n"
                "----------------\n"
                "----------------")
    elif weather_forecast in [25]: #heavy snow cloud moon
        image =("----------------\n"
                "-----------ooo--\n"
                "---------ooo----\n"
                "--------oooo----\n"
                "----www-ooo-----\n"
                "---w---w-ooo----\n"
                "-ww-----w-oo----\n"
                "w--w----www-oo--\n"
                "w------w---w----\n"
                "w----------w----\n"
                "-wwwwwwwwww-----\n"
                "---W-----W------\n"
                "------W---------\n"
                "---W-----W------")
    elif weather_forecast in [26]: #heavy snow cloud sun
        image =("----------------\n"
                "----------------\n"
                "----www---y-----\n"
                "---w---w--y--y--\n"
                "-ww-----w---y---\n"
                "w--w----www-----\n"
                "w------w---w-yy-\n"
                "w----------w----\n"
                "-wwwwwwwwww-----\n"
                "------------y---\n"
                "--W-----W-y--y--\n"
                "-----W----y-----\n"
                "--W-----W-------\n"
                "----------------")
    elif weather_forecast in [27]: #heavy snow
        image =("----------------\n"
                "----------------\n"
                "------www-------\n"
                "-----w---w------\n"
                "---ww-----w-----\n"
                "--w--w----www---\n"
                "--w------w---w--\n"
                "--w----------w--\n"
                "---wwwwwwwwww---\n"
                "----------------\n"
                "-----W-----W----\n"
                "--------W-------\n"
                "-----W-----W----\n"
                "----------------")
    elif weather_forecast in [28]: #storm cloud moon
        image =("----------------\n"
                "-----------ooo--\n"
                "---------ooo----\n"
                "--------oooo----\n"
                "----www-ooo-----\n"
                "---w---w-ooo----\n"
                "-ww-----w-oo----\n"
                "w--w----www-oo--\n"
                "w------w---w----\n"
                "w----------w----\n"
                "-ww-RRRRR-w-----\n"
                "---RRRR---------\n"
                "-----RR---------\n"
                "----R-----------")
    elif weather_forecast in [29]: #storm cloud sun
        image =("----------------\n"
                "----------------\n"
                "----www---y-----\n"
                "---w---w--y--y--\n"
                "-ww-----w---y---\n"
                "w--w----www-----\n"
                "w------w---w-yy-\n"
                "w----------w----\n"
                "-ww-RRRRR-w-----\n"
                "---RRRR-----y---\n"
                "-----RR---y--y--\n"
                "----R-----y-----\n"
                "----------------\n"
                "----------------")
    elif weather_forecast in [30]: #storm
        image =("----------------\n"
                "----------------\n"
                "------www-------\n"
                "-----w---w------\n"
                "---ww-----w-----\n"
                "--w--w----www---\n"
                "--w------w---w--\n"
                "--w----------w--\n"
                "---ww-RRRRR-w---\n"
                "-----RRRR-------\n"
                "-------RR-------\n"
                "------R---------\n"
                "----------------\n"
                "----------------")
    elif weather_forecast in [31]: #hurricane
        image =("----------------\n"
                "------R---RR----\n"
                "-----R---R------\n"
                "-----R--R-------\n"
                "--R--RRRRRRRRR--\n"
                "---R-RRRRRR---R-\n"
                "----RRRRRRRR----\n"
                "-R---RRRRRR-R---\n"
                "--RRRRRRRRR--R--\n"
                "-------R--R-----\n"
                "------R---R-----\n"
                "----RR---R------\n"
                "----------------")
    else: #mixed
        image =("rrrrrrrrrrrrrrrr\n"
                "oooooooooooooooo\n"
                "yyyyyyyyyyyyyyyy\n"
                "GGGGGGGGGGGGGGGG\n"
                "BBBBBBBBBBBBBBBB\n"
                "bbbbbbbbbbbbbbbb\n"
                "mmmmmmmmmmmmmmmm\n"
                "rrrrrrrrrrrrrrrr\n"
                "oooooooooooooooo\n"
                "yyyyyyyyyyyyyyyy\n"
                "GGGGGGGGGGGGGGGG\n"
                "BBBBBBBBBBBBBBBB\n"
                "bbbbbbbbbbbbbbbb\n"
                "mmmmmmmmmmmmmmmm")

    return image
