from page import Page

class GamePage(Page):
    def __init__(self, number, text, options=[]):
        super(GamePage, self).__init__(number)
        self.title = "Choose your own adventure"
        self.in_index = False
        self.text = text
        self.importance = 0
        self.options = options

    def generate_content(self):
        from random import shuffle
        self.add_title("Find the dragon",font="size4")
        self.add_newline()
        self.add_wrapped_text(self.text)
        if len(self.options)>0:
            self.add_newline()
            self.add_newline()
            self.add_text("What do you want to do?")
            self.add_newline()
            shuffle(self.options)
            for o,n in self.options:
                self.add_text("  "+o)
                self.add_text(" Go to "+n,fg="RED")
                self.add_newline()

page00 = GamePage("900","There is a dragon loose in the EMF site. Your job is to track it down and prevent it from doing any more damage.",[("Go to stage A","932"),("Go to stage B","916")])
page00.in_index = True
page00.importance = 4
page01 = GamePage("901","You walk away from the amateur radio village.",[("Go to the lake","937"),("Go to the Youth workshops","970")])
page02 = GamePage("902","The dragon burns the bean bag before it get near to it.",[("Continue","931")])
page03 = GamePage("903","A Belgian tells you that the dragon is in the lounge and offers you a lift there on a golf cart.",[("Go with the Belgin to the lounge","941"),("Get the Belgians to help you build a hiding place","915")])
page04 = GamePage("904","The survivor tells you that he saw the dragon burn down stage C then head towards the Maths Village",[("Go to the Maths Village","963")])
page05 = GamePage("905","You drink whisky.",[("Drink whisky","909")])
page06 = GamePage("906","You play on your badge as the dragon burns down the camp around you. GAME OVER.")
page07 = GamePage("907","You go to the Amateur Radio village. In the village there is a group of amateur radio operators.",[("Get the radio operators to call for help","994"),("Say \"CQ CQ\"","921")])
page08 = GamePage("908","The tables and bean bags are not big enough to harm the dragon.",[("Continue","995")])
page09 = GamePage("909","You drink whisky",[("Drink whisky","978")])
page10 = GamePage("910","At Camp Holland you are given stroopwaffels. You eat so much that the person next to you gives you their volunteer food token, as they won't be needing it any more.",[("Take a digestive nap","945")])
page11 = GamePage("911","At the Belgian Embassy, you meet some Belgians.",[("Ask the Belgians about the dragon","903")])
page12 = GamePage("912","The people at the Swansea Hackspace village assure you that the dragon the child saw was on a Welsh flag.",[("Go to the Belgian Embassy","911")])
page13 = GamePage("913","You go to the badge tent. You are given your badge.",[("Play with your badge","906"),("Help to fix other people's badges.","972")])
page14 = GamePage("914","The man in the orange suit is from Camp Holland. He tells you to drop by for stroopwaffels.",[("Go to Camp Holland","910"),("Go to the bar","999")])
page15 = GamePage("915","You build a hiding place with the Belgians and hide there as the dragon destroys the rest of the site. The dragon then gets bored and flies away. You're not sure if you've won or lost... GAME OVER and/or CONGRATULATIONS!")
page16 = GamePage("916","You arrive at stage B as a talk is ending. People are leaving the marquee.",[("Talk to the man in the orange suit","914"),("Talk to Jonty","984")])
page17 = GamePage("917","You creep forwards and spot the dragon to the right of the tent.",[("Continue","966")])
page18 = GamePage("918","You punch the dragon. It punches you back. With fire. GAME OVER")
page19 = GamePage("919","On your way to take a nap, you trip and bash your nose. You die of embarrasment. GAME OVER.")
page20 = GamePage("920","You talk the members of Bristol Hackspace. They have heard that the dragon is in the Lounge.",[("Head towards the lounge","954"),("Take a nap first","919")])
page21 = GamePage("921","The amateur radio operators are offended and expel you from their village.",[("Continue","901")])
page22 = GamePage("922","You are sent to prison for murder. GAME OVER.")
page23 = GamePage("923","You head to the food vendors.",[("Eat","947")])
page24 = GamePage("924","You proceed with caution from front door. You spot the dragon to the left of the lounge.",[("Continue","966")])
page25 = GamePage("925","You meet Maths Village Matt Scroggs, who wrote this game. You ask him how to win this game, but he tells you off for cheating.",[("Help Matt Parker with his traps","996"),("See who else is around","955")])
page26 = GamePage("926","Your volunteer shift is in the retro game tent. The only dragons around are made of pixels. At the end of your shift you are given a token for free volunteer food.",[("Go eat volunteer food","943")])
page27 = GamePage("927","You are thrown out of the camp for yelling all night in the quiet camping area. GAME OVER.")
page28 = GamePage("928","You find a survivor under the smoking tent.",[("Ask the survivor where the dragon went","904"),("Take the survivor to the first aid tent.","950")])
page29 = GamePage("929","You are in the quiet camping area.",[("Tell the campers to run away from the dragon","967"),("Ask the campers for information","953")])
page30 = GamePage("930","The dragon hears you running and yelling and burns you to a crisp. Ouch. GAME OVER.")
page31 = GamePage("931","You are fighting a dragon.",[("Throw a bean bag at the dragon","902"),("Punch the dragon","918"),("Try to reason with the dragon","936"),("Ask the people in the lounge to help","998"),("Look around the lounge for equipment","965")])
page32 = GamePage("932","At stage A, you meet a volunteer. She was introducing the current speaker when she saw the dragon walk past heading towards stage C.",[("Go to Stage C","934")])
page33 = GamePage("933","You look around and find a collection of bottles of water, beer and Club Mate.",[("Pour the liquid on the dragon","989")])
page34 = GamePage("934","You arrive at stage C to find the smoking remains of the stage.",[("Look for survivors","928"),("Go to the bar","999")])
page35 = GamePage("935","You drink whisky.",[("Drink whisky","909")])
page36 = GamePage("936","The dragon doesn't understand English.",[("Continue","931")])
page37 = GamePage("937","You go to the lake and jump in for a swim. Unfortunately, you cannot swim. You drown. GAME OVER")
page38 = GamePage("938","You leave the site and walk across the car park.",[("Continue","951")])
page39 = GamePage("939","The dragon lets out a great roar... then falls. CONGRATULATIONS! YOU WIN.")
page40 = GamePage("940","You are caught stealing and sent to prison forever. GAME OVER")
page41 = GamePage("941","The Belgian drops you off near the lounge.",[("Continue on foot","976")])
page42 = GamePage("942","The people from Nottingham tell you that the dragon walked past them on its way to the Bristol Hackspace village.",[("Go to the Bristol Hackspace village.","948")])
page43 = GamePage("943","At the volunteer food tent, you are given a hearty meal. You decide that you should do as many volunteer shifts as you can to get this excellent food. While you are eating, you overhear someone talking about seeing the dragon in the quiet camping area.",[("Do a volunteer shift","960"),("Go the the quiet camping area","929")])
page44 = GamePage("944","You finish helping Matt balance the stellated dodecahedron on the egde of the tent, ready to fall on the dragon. He thanks you, and tells you to talk to Maths Village resident Katie Steckles, as she has information about the dragon.",[("Talk to Katie","955")])
page45 = GamePage("945","You wake up in Camp Holland 30 minutes later. Let's hope the dragon hasn't killed too many people while you were asleep.",[("Go eat volunteer food","943"),("Go to the Nottingham Hackspace village","980")])
page46 = GamePage("946","You trip over a bean bag and break all the bones in your body. First aid cannot save you. GAME OVER.")
page47 = GamePage("947","You are now less hungry.",[("Continue to the lounge","976")])
page48 = GamePage("948","You go to the Bristol Hackspace village.",[("Ask the villagers for information","920"),("Take a nap in the village's tent","919")])
page49 = GamePage("949","You pick up a snack from your tent and eat it.",[("Continue to the lounge","976"),("Go to the Belgian Embassy","911")])
page50 = GamePage("950","You help the survivor to the first aid tent. The first aiders ask you to go the bar to get some water.",[("Go to the bar","999"),("Talk to the survivor","956")])
page51 = GamePage("951","In the car park, you are run over by the shuttle bus. GAME OVER.")
page52 = GamePage("952","You go to Whiskyleaks.",[("Drink whisky","905")])
page53 = GamePage("953","You talk to the quiet campers. They tell you that the dragon seen in their area was actually a kite build by one of their children. They tell you that they are yet to receive today's post.",[("Go to Camp Postal","969"),("Go to the HQ tent","968")])
page54 = GamePage("954","You leave Bristol Hackspace and head towards the lounge.",[("Continue","971")])
page55 = GamePage("955","You find and talk to Katie Steckles, a resident of the Maths Village. She tells you that the dragon is currently hiding in the lounge.",[("Go to the lounge","975"),("Steal Katie's laptop","940")])
page56 = GamePage("956","You ask the survivor for information.",[("Listen","904"),("Run away to the car park","938")])
page57 = GamePage("957","You head to the volunteer kitchen. While eating your delicious meal, you meet Benny, who has been helping with setup.",[("Ask Benny about the dragon","991"),("Go with Benny to the HQ tent","968")])
page58 = GamePage("958","You were meant to destroy the Sith, not join them. GAME OVER")
page59 = GamePage("959","The dragon doesn't understand surrender and burns you all. GAME OVER.")
page60 = GamePage("960","You volunteer to introduce the speakers in stage A. After your volunteer shift you get another food token.",[("Go eat volunteer food","557"),("Go to Camp Postal","968")])
page61 = GamePage("961","You drink whisky.",[("Drink whisky","635")])
page62 = GamePage("962","You enter the lounge through the back door. No sign of the dragon yet.",[("Proceed with caution","917"),("Proceed without caution","946")])
page63 = GamePage("963","At the Maths Village, you meet stand up mathematician Matt Parker. Matt is building a collection of mathematical traps to catch the dragon",[("Help Matt build traps","996"),("See who else is around","925")])
page64 = GamePage("964","You head into the HQ, where you meet David.",[("Ask David about the network","972"),("Go to the lounge","976"),("Kill David","922")])
page65 = GamePage("965","You find a sword under one of the bean bags.",[("Slay the dragon with the sword","992")])
page66 = GamePage("966","The dragon turns to face you. Time to fight.",[("Begin fight","931")])
page67 = GamePage("967","No-one is listening to you.",[("Tell them more loudly","927"),("Ask the campers for information","953"),("Go to the Nottingham Hackspace village","980")])
page68 = GamePage("968","At the HQ tent, you meet Russ. Russ has heard on the radio that the dragon is in the lounge. Russ cannot fight the dragon himself, though, as he is on his way to Whiskyleaks.",[("Go with Russ to Whiskyleaks","952"),("Head to the lounge to fight the dragon","976"),("See who else is at the HQ","964")])
page69 = GamePage("969","You arrive at Camp Postal. It has been abandoned. There are a few smoking tents around the village. There is a large pile of undelivered letters.",[("Open a letter","988"),("Go to the Bristol Hackspace village","948")])
page70 = GamePage("970","You go the Youth Workshop tent. Inside, children are building kites.",[("Build a kite","986"),("Ask if anyone has seen the dragon","993")])
page71 = GamePage("971","It's a long walk to the lounge. You get hungry.",[("Go to the food vendors","923"),("Ignore your hunger","981"),("Head to your tent to pick up a snack","949")])
page72 = GamePage("972","David tells you about the network.",[("Go to the lounge","976")])
page73 = GamePage("973","RecursionError: maximum recursion depth exceeded. GAME OVER")
page74 = GamePage("974","You are on the roof of the marquee in the Maths Village building a stellated dodecahedron to drop on the dragon.",[("Jump down and see who is around to talk to","979"),("Finish setting up the trap","944")])
page75 = GamePage("975","You walk towards the lounge.",[("Creep closer to the lounge","987")])
page76 = GamePage("976","You walk over to the lounge. There are two entrances.",[("Enter through the front entrance","990"),("Enter through the back entrance","962"),("Burn the lounge down","982")])
page77 = GamePage("977","You attach a camera to your kite and head outside to take aerial photos.",[("Look at your photos","983"),("Kill younglings","958")])
page78 = GamePage("978","You drink whisky.",[("Drink whisky","961")])
page79 = GamePage("979","You jump off the roof, but the stellated dodecahedron rolls off after you and squishes you. You are very squished and the first aid tent cannot save you. GAME OVER.")
page80 = GamePage("980","At the Nottingham Hackspace village, you meet some people from Nottingham.",[("Talk to the people from Nottingham","942")])
page81 = GamePage("981","You die of hunger. GAME OVER.")
page82 = GamePage("982","You burn the lounge down, but the dragon survives as it is immune to fire. You are sent to prison for killing everyone inside the lounge. GAME OVER")
page83 = GamePage("983","In one of your photos, you see the dragon's tail poking out of the side of the lounge.",[("Go the the lounge","976")])
page84 = GamePage("984","Jonty tells you that you should sign up for a volunteer shift.",[("Do a volunteer shift","926"),("Go to Camp Holland","910")])
page85 = GamePage("985","You are driving around in a golf cart.",[("Go to the Amateur Radio village","907"),("Go the the Bristol Hackspace village","948"),("Go to the badge tent","913")])
page86 = GamePage("986","You build a kite. The childen attach cameras to their kites and head outside to take aerial photos.",[("Attach a camera to your kite","977")])
page87 = GamePage("987","You creep closer to the lounge. There are two entrances.",[("Enter through the front entrance","990"),("Enter through the back entrance","962"),("Burn the lounge down","982")])
page88 = GamePage("988","You open a letter. It is an invitation to Whiskyleaks",[("Go to the Bristol Hackspace village","948"),("Go to Whiskyleaks","952")])
page89 = GamePage("989","The liquid puts the dragon's fire out. It dies. CONGRATULATIONS! YOU WIN.")
page90 = GamePage("990","You enter the lounge through the front door. No sign of the dragon yet.",[("Proceed with caution","924"),("Proceed without caution","930")])
page91 = GamePage("991","You ask Benny about the dragon. He doesn't know where it is, but tells you to that he can drive you about in a golf cart to look for it.",[("Go in the golf cart","985")])
page92 = GamePage("992","You run at the dragon and swipe...",[("Continue","939")])
page93 = GamePage("993","One of the children says he saw the dragon in the Swansea Hackspace village.",[("Go to the Swansea Hackspace village","912"),("Build a kite","986")])
page94 = GamePage("994","You wait for the army to arrive. They slay the dragon. CONGRATULATIONS! YOU WIN.")
page95 = GamePage("995","Your army is fighting the dragon.",[("Throw bean bags and tables at the dragon","908"),("Look around for equipment","933"),("Surrender","959")])
page96 = GamePage("996","Matt tells you to climb onto the roof of the Maths Village marquee to build a giant stellated dodecahedron to drop on the dragon.",[("Climb on the roof","974"),("See who else is around","955")])
page97 = GamePage("997","As you leave the bar sipping your Club Mate, you wander into the Nottingham Hackspace village.",[("Continue","980")])
page98 = GamePage("998","You assemble a small army of hackers.",[("Continue","995")])
page99 = GamePage("999","At the bar, there is no-one around, but no sign of fire damage.",[("Go to the car park","951"),("Help yourself to a Club Mate","997"),("Play the text based adventure game on EMFFAX","973")])
